version: '3'

services:
  postgres:
    image: postgres
    volumes:
    - ./volumes/postgresql:/var/lib/postgresql
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: chatbot
  chatbot:
    build: .
    volumes:
    - ./chatbot:/chatbot
    - ./volumes/log/chatbot:/var/log/chatbot
    - ./volumes/log/gunicorn:/var/log/gunicorn
    environment:
      SECRET_KEY: notverysecret
      DATABASE: postgresql://pguser:pgpass@postgres/chatbot
      LOG_DIR: /var/log/chatbot
    depends_on:
    - postgres
  nginx:
    image: nginx
    volumes:
    - ./chatbot:/chatbot
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./volumes/log/nginx:/var/log/nginx/
    ports:
    - "8080:80"
    depends_on:
    - chatbot
